// Generated by scripts/i18n-types.mjs from en.json. Do not edit by hand.
export const I18N_KEYS = ['alerts', 'open', 'sub', 'title', 'updated'] as const;
export type I18nKey = (typeof I18N_KEYS)[number];
