#!/usr/bin/env node
// Generates src/i18n/keys.gen.ts from en.json. With --check, fails if the generated file is stale or
// any locale is missing (or has extra) keys. CI runs the check, so an untranslated string cannot ship.
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'i18n');
const check = process.argv.includes('--check');

const read = async (file) => JSON.parse(await readFile(join(dir, file), 'utf8'));
const en = await read('en.json');
const keys = Object.keys(en).sort();

const generated = `// Generated by scripts/i18n-types.mjs from en.json. Do not edit by hand.
export const I18N_KEYS = [${keys.map((k) => `'${k}'`).join(', ')}] as const;
export type I18nKey = (typeof I18N_KEYS)[number];
`;

const problems = [];
for (const file of (await readdir(dir)).filter((f) => f.endsWith('.json') && f !== 'en.json')) {
  const locale = Object.keys(await read(file));
  const missing = keys.filter((k) => !locale.includes(k));
  const extra = locale.filter((k) => !keys.includes(k));
  if (missing.length) problems.push(`${file}: missing ${missing.join(', ')}`);
  if (extra.length) problems.push(`${file}: unknown ${extra.join(', ')}`);
}

const target = join(dir, 'keys.gen.ts');
if (check) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== generated) problems.push('keys.gen.ts is stale: run `npm run i18n:types`');
  if (problems.length) {
    console.error(`i18n check failed:\n  ${problems.join('\n  ')}`);
    process.exit(1);
  }
  console.log(`i18n check passed: ${keys.length} keys in every locale`);
} else {
  await writeFile(target, generated);
  console.log(`wrote src/i18n/keys.gen.ts (${keys.length} keys)`);
  if (problems.length) console.warn(`warning:\n  ${problems.join('\n  ')}`);
}
